config-sparse:
  modules:
    ucp2-legacy:
      config:
        o_freetrader:
          enabled:
            contents:
              required-value: false
        u_arabxbow:
          enabled:
            contents:
              required-value: false
        u_laddermen:
          enabled:
            contents:
              required-value: false
        u_spearmen:
          enabled:
            contents:
              required-value: false
        o_shfy:
          o_shfy_beer:
            enabled:
              contents:
                required-value: false
          o_shfy_religion:
            enabled:
              contents:
                required-value: false
          o_shfy_peasantspawnrate:
            enabled:
              contents:
                required-value: false
          o_shfy_resourcequantity:
            enabled:
              contents:
                required-value: false
    rebalancer:
      config: {}
  plugins: {}
meta:
  version: 1.0.0
