return {
    building_names = {
        "Hovel",
        "House",
        "Woodcutter hut",
        "Ox tether",
        "Iron mine",
        "Pitch rig",
        "Hunters hut",
        "Mercenary post",
        "Barracks",
        "Stockpile",
        "Armory",
        "Fletcher",
        "Blacksmith",
        "Poleturner",
        "Armourer",
        "Tanner",
        "Bakery",
        "Brewery",
        "Granary",
        "Quarry",
        "Quarrypile",
        "Inn",
        "Apothecary",
        "Engineers guild",
        "Tunnelers guild",
        "Marketplace",
        "Well",
        "Oil smelter",
        "Siege tent",
        "Wheat farm",
        "Hop farm",
        "Apple farm",
        "Dairy farm",
        "Mill",
        "Stables",
        "Chapel",
        "Church",
        "Cathedral",
        "Ruins",
        "Keep one",
        "Keep two",
        "Keep three",
        "Keep four",
        "Keep five",
        "Large gatehouse",
        "Small gatehouse",
        "Main wood",
        "Postern gate",
        "Drawbridge",
        "Tunnel",
        "Campfire",
        "Signpost",
        "Parade ground",
        "Fire ballista",
        "Campground",
        "Parade ground",
        "Parade ground",
        "Parade ground",
        "Parade ground",
        "Gatehouse",
        "Tower",
        "Gallows",
        "Stocks",
        "Witch hoist",
        "Maypole",
        "Garden",
        "Killing pit",
        "Pitch ditch",
        "unused",
        "Water pot",
        "Keepdoor left",
        "Keepdoor right",
        "Keepdoor",
        "Tower one",
        "Tower two",
        "Tower three",
        "Tower four",
        "Tower five",
        "unused2",
        "Catapult",
        "Trebuchet",
        "Siege tower",
        "Battering ram",
        "Portable shield",
        "unused3",
        "Mangonel",
        "Tower Ballista",
        "unused4",
        "unused5",
        "unused6",
        "Cesspit",
        "Burning stake",
        "Gibbet",
        "Dungeon",
        "Stretching rack",
        "Flogging rack",
        "Chopping block",
        "Dunking stool",
        "Dog cage",
        "Statue",
        "Shrine",
        "Bee hive",
        "Dancing bear",
        "Pond",
        "Bear cave",
        "European Outpost",
        "Mercenary Outpost"
    },
    unit_names = {
        "Peasant",
        "Burning man",
        "Woodcutter",
        "Fletcher",
        "Tunneler",
        "Hunter",
        "Quarry mason",
        "Quarry grunt",
        "Quarry ox",
        "Pitch worker",
        "Wheat farmer",
        "Hops farmer",
        "Apple farmer",
        "Dairy farmer",
        "Miller",
        "Baker",
        "Brewer",
        "Poleturner",
        "Blacksmith",
        "Armourer",
        "Tanner",
        "European archer",
        "European crossbowman",
        "European spearman",
        "European pikeman",
        "European maceman",
        "European swordsman",
        "European knight",
        "Ladderman",
        "Engineer",
        "Iron miner1",
        "Iron miner2",
        "Priest",
        "Healer",
        "Drunkard",
        "Innkeeper",
        "Monk",
        "unknown1",
        "Catapult",
        "Trebuchet",
        "Mangonel",
        "Trader",
        "Trader horse",
        "Deer",
        "Lion",
        "Rabbit",
        "Camel",
        "Crow",
        "Seagull",
        "Siege tent",
        "Cow",
        "Hunter dog",
        "Fireman",
        "Ghost",
        "Lord",
        "Lady",
        "Jester",
        "Siege tower",
        "Battering ram",
        "Portable shield",
        "Tower ballista",
        "Chicken",
        "Mother",
        "Child",
        "Juggler",
        "Fireeater",
        "Dog",
        "unknown2",
        "unknown3",
        "Arabian archer",
        "Arabian slave",
        "Arabian slinger",
        "Arabian assassin",
        "Arabian horse archer",
        "Arabian swordsman",
        "Arabian firethrower",
        "Fire ballista"
    },
    military_ground_unit_names = {
    "European archer",
    "European crossbowman",
    "European spearman",
    "European pikeman",
    "European maceman",
    "European swordsman",
    "European knight",
    "Ladderman",
    "Engineer",
    "Monk",
    "Tunneler",
    "Arabian archer",
    "Arabian slave",
    "Arabian slinger",
    "Arabian assassin",
    "Arabian horse archer",
    "Arabian swordsman",
    "Arabian firethrower",
    "Fire ballista",
    "Catapult"
    },
    resource_names = {
        "Wood",
        "Hop",
        "Stone",
        "Blank1",
        "Iron",
        "Pitch",
        "Blank2",
        "Wheat",
        "Bread",
        "Cheese",
        "Meat",
        "Fruit",
        "Beer",
        "Blank3",
        "Flour",
        "Bow",
        "Xbow",
        "Spear",
        "Pike",
        "Mace",
        "Sword",
        "Leather",
        "Armor"
    },
    pop_thresholds = {
        "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100"
    }
}


